namespace ClinicSystem.Infrastructure.MedicalRecords;

public sealed record PatientMedicalIntakeDto(
    Guid PatientId,
    string FullName,
    string PhoneNumber,
    string? AlternatePhone,
    DateOnly? DateOfBirth,
    string? Gender,
    string? MaritalStatus,
    string? Occupation,
    string? Address,
    bool HasDrugAllergy,
    string? DrugAllergyDetails,
    bool HasHypertension,
    bool HasRheumaticFever,
    bool HasBloodDisease,
    bool HasLiverDisease,
    bool HasHepatitis,
    bool HasDiabetes,
    bool HasHeartDisease,
    bool HasKidneyDisease,
    bool HasThyroidDisease,
    bool HasCancer,
    string? OtherConditions,
    bool HadRecentHospitalization,
    string? RecentHospitalizationReason,
    string? MedicalNotes,
    string? PatientSignatureName,
    DateOnly? FormDate,
    DateTime? UpdatedAtUtc
);

public sealed record UpdatePatientMedicalIntakeCommand(
    string FullName,
    string PhoneNumber,
    string? AlternatePhone,
    DateOnly? DateOfBirth,
    string? Gender,
    string? MaritalStatus,
    string? Occupation,
    string? Address,
    bool HasDrugAllergy,
    string? DrugAllergyDetails,
    bool HasHypertension,
    bool HasRheumaticFever,
    bool HasBloodDisease,
    bool HasLiverDisease,
    bool HasHepatitis,
    bool HasDiabetes,
    bool HasHeartDisease,
    bool HasKidneyDisease,
    bool HasThyroidDisease,
    bool HasCancer,
    string? OtherConditions,
    bool HadRecentHospitalization,
    string? RecentHospitalizationReason,
    string? MedicalNotes,
    string? PatientSignatureName,
    DateOnly? FormDate
);
